# app/main.py
from pathlib import Path

from fastapi import FastAPI, Request
from fastapi.responses import HTMLResponse
from fastapi.staticfiles import StaticFiles

from .scoring import score_transcript

app = FastAPI()

# ------------------------------------------------------------------
# Resolve project paths in a robust way (works locally + in deployment)
# ------------------------------------------------------------------
# /path/to/AI-TranscriptScoring/app/main.py
BASE_DIR = Path(__file__).resolve().parents[1]   # -> /path/to/AI-TranscriptScoring
FRONTEND_DIR = BASE_DIR / "frontend"             # -> /path/to/AI-TranscriptScoring/frontend

# Mount static files (CSS + JS) from the frontend folder
app.mount(
    "/static",
    StaticFiles(directory=str(FRONTEND_DIR)),
    name="static",
)


# ------------------------------------------------------------------
# Routes
# ------------------------------------------------------------------

@app.get("/", response_class=HTMLResponse)
def home() -> HTMLResponse:
    """
    Serve the main HTML page.
    We read index.html from the frontend folder using an absolute path,
    so it works regardless of where uvicorn is started from.
    """
    index_path = FRONTEND_DIR / "index.html"
    html = index_path.read_text(encoding="utf-8")
    return HTMLResponse(content=html)


@app.post("/api/score")
async def score_api(req: Request):
    """
    Accepts JSON:
      { "transcript": "...", "duration": 52 }
    Returns the scoring JSON generated by score_transcript().
    """
    data = await req.json()

    transcript = (data.get("transcript") or "").strip()
    duration = data.get("duration", 52)

    try:
        duration = float(duration)
    except (TypeError, ValueError):
        duration = 52.0

    if not transcript:
        return {"error": "Transcript is required."}

    result = score_transcript(transcript, duration_sec=duration)
    return result
